apiVersion: v1
kind: Namespace
metadata:
  name: cnpe-pdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: cnpe-pdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-pdb
  namespace: cnpe-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: WRONG

