apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-reader-role
  namespace: cnpe-rbac-min
rules:
- apiGroups: [""]
  resources: [configmaps]
  verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-reader-binding
  namespace: cnpe-rbac-min
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-reader-role
subjects:
- kind: ServiceAccount
  name: app-reader
  namespace: cnpe-rbac-min
