apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platform-engineer-battleground
  description: Platform engineering practice scenarios
  annotations:
    backstage.io/techdocs-ref: dir:docs
spec:
  type: library
  owner: guests
  lifecycle: experimental
