apiVersion: v1
kind: Secret
metadata:
  name: payment-db-connection
  namespace: cnpe-eso-test
type: Opaque
data:
  # "super-secure-password-123" base64 encoded
  DB_PASSWORD: c3VwZXItc2VjdXJlLXBhc3N3b3JkLTEyMw==
