apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpe-packaging

resources:
- ../../base

# TODO: Add your patches here to:
# 1. Change replicas to 3
# 2. Add memory limit 512Mi
# 3. Add suffix -prod
